from . import common
from . import test_phase06_deployment
from . import test_phase07_contact_binding
from . import test_phase08_multi_tenant
from . import test_phase09_https_proxy
from . import test_phase10_fault_recovery
from . import test_phase11_monitoring
from . import test_phase12_data_governance
from . import test_phase13_operations
